### ISSUE TITLE
Large WGS file

### ISSUE THREAD

**Issue by ghost** [mobidic/knotAnnotSV#12]
Hi there,

I've come up against an error when loading an approx. 50 Mb file via html. Does knotAnnotSV have a way to visualise large files of this sort? 

Best wishes

**Comment by kvn95ss** [comment]
Hello,

I had a similar issue. I used Delly on WGS sample. Turns out lot of the calls were false positive. I filtered out CNVs using an arbitrary cut off, PE (paired end reads supporting the SV) > 5 and SR (Split reads supporting the SV) > 9. This filters a lot of the false calls, now the annotated file has fewer entries.

**Comment by thomasguignard** [comment]
Hello,

You can take a look at the newly uploaded knotAnnotSV2XL.pl script in this repo. 
You will be able to open the output on a classic spreadsheet.

My test with a huge 45000 lines annotSV ouput gives me a 7Mo xlsm file.

Hope this helps.

**Comment by thomasguignard** [comment]
Please note that the relative command line has changed slightly (vbaBin is added automatically, check README) :
perl ./knotAnnotSV2XL.pl --annotSVfile ./example/example.annotated.tsv --configFile ./config_AnnotSV.yaml  --outDir ./example
